name: lint-source

on: [push]

jobs:
  lint-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 15]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn
      - name: Check code style
        run: yarn format:check
      - name: Check code quality
        run: yarn lint
