name: lint-source

on: [push]

jobs:
  lint-source:
    runs-on: ubuntu-latest
    container: boringcodes/dev-runner:node-${{matrix.node-version}}-alpine
    strategy:
      matrix:
        node-version: [10, 12, 14, 15]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Check code style
        run: yarn format:check
      - name: Check code quality
        run: yarn lint
