name: publish-npm

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 15]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
