name: publish-npm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
      - name: Publish package
        run: yarn publish build --access public
        env:
          # Create your own token at https://github.com/organization/repository/settings/secrets
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
