name: publish-npm

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
      - name: Copy files
        run: cp package.json build/package.json
      - name: Publish package
        run: yarn publish build --access public
        env:
          # Create your own token at https://github.com/organization/repository/settings/secrets
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
