name: publish-npm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build source
        run: yarn build
      - name: Copy files
        run: cp package.json build/package.json
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          package: build/package.json
          access: public
          # Create your own token at https://github.com/organization/repository/settings/secrets
          token: ${{secrets.NPM_TOKEN}}
          check-version: false
